services:
  warehouse-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-frontend
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3050:80"
    # 빌드한 폴더를 복사해서 배포합니다. 별도 배포 명령어 실행안함.
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./dist:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    networks:
      - npm-network

networks:
  npm-network:
    external: true
